hello大家好，在机器学习与人工智能燃烧全球的当下，小编也随大流为大家送上了机器学习与AI的基础内容
(Numpy科学计算库的使用)，好吧，我承认自己不会扯犊子，那么我们就直接进入主题，What's numpy?

In [ ]:
Numpy简介：
    numpy是Numerical Python的简称，是用于数据科学计算的基础模块，不但能够完成科学计算的任务，而且能够用作
    高效的多为数据容器，可用于存储和处理大型矩阵(矩阵概念请移驾线性代数，此处不做解释)
    虽然python是用于通用编程的优秀工具，具有高度可读的语法和丰富强大的数据类型(字符串，列表，集合，字典和数值等)
    以及非常全面的标准库，但是他并没有提供数组功能（虽然python中列表功能及其强大），为此Numpy提供了真正的数组功能
    以及对数据进行快速处理的函数，这就是numpy
numpy安装：
    安装numpy与其他第三方库一样，可以通过pip安装
        pip install numpy
    或者自行下载源代码，然后
        python setup.py install
    上述方法适用win环境编程和linux环境编程，在linux环境中，好多发行版的软件源都有python常见的库
    因此可以利用linux软件管理方式安装，如Ubuntu中：
        sudo apt-get install python-numpy 
numpy参考链接：
    http://www.numpy.org/     #官网是最好的学习手册
    https://www.numpy.org.cn/    #numpy中文文档
    http://www.runoob.com/numpy/numpy-tutorial.html  #菜鸟教程

#### 数组与列表的异同

In [1]:
#首先用熟悉的列表对比陌生的数组，进而初步认识什么是数组
import numpy as np    #导入numpy包
LIST = [1,3,5,7,9]
ARR = np.array([1,3,5,7,9])
print('LIST的值为:{},类型为：{}'.format(LIST,type(LIST)))
print('ARR的值为：{},类型为：{}'.format(ARR,type(ARR)))

LIST的值为:[1, 3, 5, 7, 9],类型为：<class 'list'>
ARR的值为：[1 3 5 7 9],类型为：<class 'numpy.ndarray'>


In [ ]:
通过上面的例子我们发现，LIST依旧是我们的列表，而ARR的类型变成了<class 'numpy.ndarray'>这个对象
那么我们就从<class 'numpy.ndarray'>这个对象说起

#### 数组对象ndarray
- numpy提供了俩种基本对象：ndarray(N-dimensional Array Object)和ufunc(Universal Function Object)
- ndarray(下文统一称为数组)是存储单一数据类型的多为数组
- 而ufunc则是能够对数组进行处理的函数

#### 数组属性
    为了更好的理解和使用数组，在创建数组之前，我们先了解了解数组的基本属性
- ndim：返回int，表示数组的维数
- shape：返回tuple，表示数组的尺寸，对于n行m列的矩阵，形状为(n,m)
- size：返回int，表示数组的元素总数，等于数组形状的乘积
- dtype：返回数组中的数据类型，注意的是数组中的数据类型相同
- itemsize：返回int，表示每个元素的大小（单位字节）

#### 数组创建
numpy提供的array函数可以创建一维或多维数组，基本语法如下：

numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

参数说明：

    1.object：接受array，表示想要创建的数组，无默认
    2.dtype：接受数据类型，表示数组所需的数据类型
    3.ndim：接受int，指定生成数组应该具有的最小维数，默认为None
    

In [5]:
#创建数组并查看数组属性
arr1 = np.array([1,2,3,4,5])  #创建一个数组
print('创建的数组为：',arr1)

创建的数组为： [1 2 3 4 5]


In [11]:
#创建二维数组
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('创建的数组为：\n',arr2)

创建的数组为：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
#二维数组其实就是列表的一种嵌套功能，也可以这样创建：
list_1 = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]
arr3 = np.array(list_1)
print('新创建的二维列表为：\n',arr3)

新创建的二维列表为：
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
#甚至也可以看前面有几个方括号就是几维的数组，三维或者更高维的数组依次类推

In [21]:
#查看数组结构
print('数组维度为：',arr3.shape)   #输出结果代表三行四列

数组维度为： (3, 4)


In [18]:
#查看数组类型
print('数组类型为：',arr3.dtype)

数组类型为： int32


In [19]:
#查看数组元素个数
print('数组元素个数为：',arr3.size)

数组元素个数为： 12


In [20]:
#查看数组每个元素大小
print('数组每个元素大小为：',arr3.itemsize)

数组每个元素大小为： 4


In [26]:
#重新设置数组的shaoe属性
print('arr3数组的结构为：',arr3.shape)
arr3.shape = 4,3  #重新设置shape
print('重新设置shape后的arr3的结构为：',arr3.shape)

arr3数组的结构为： (3, 4)
重新设置shape后的arr3的结构为： (4, 3)


In [35]:
#使用arange函数创建数组
arr4 = np.arange(0,1,0.1)
print('arr4数组为：',arr4)
print('arr4数组结构为:',arr4.shape)
arr4.shape = 2,5
print('改变结构的新数组为：\n',arr4)
print('改变结构的新数组结构为：',arr4.shape)

arr4数组为： [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
arr4数组结构为: (10,)
改变结构的新数组为：
 [[0.  0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8 0.9]]
改变结构的新数组结构为： (2, 5)


In [47]:
#上述操作可以直接改为如下操作
arr5 = np.arange(0,20,1).reshape((4,5))
print(arr5)
print(arr5.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)


#### numpy常用函数操作

In [51]:
#linspace函数通过指定开始值，终值和元素个数来创建一维数组，默认包含终值
arr6 = np.linspace(0,1,12)
print(arr6)
print('………………………………')
arr6.shape = 3,4
print(arr6)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]
………………………………
[[0.         0.09090909 0.18181818 0.27272727]
 [0.36363636 0.45454545 0.54545455 0.63636364]
 [0.72727273 0.81818182 0.90909091 1.        ]]


In [52]:
#logspace函数和linspace函数类似，他创建的是等比数列
#生成1（10^0）～100（10^2）的20个元素的等比数列
arr7 = np.logspace(0,2,10)
print(arr7)

[  1.           1.66810054   2.7825594    4.64158883   7.74263683
  12.91549665  21.5443469   35.93813664  59.94842503 100.        ]


In [54]:
#使用zeros函数用来创建值全为0的数组,即创建的数组值全部填充为0
arr8 = np.zeros((2,3))  #创建俩行三列的值全为0的数组
print(arr8)

[[0. 0. 0.]
 [0. 0. 0.]]


In [55]:
#eye函数用来生成主对角线元素为1，其他元素为0的数组，类似单位矩阵
arr9 = np.eye(3)   #创建三行三列的方阵
print(arr9)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [56]:
#diag函数用来创建类似对角的数组，即除对角线以外的其他元素都是0，对角线得到元素可以是0或其他值
arr10 = np.diag([1,2,3,4])  #指定主对角线数值
print(arr10)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [57]:
#ones函数用来创建元素全部为1的数组，即创建的数组元素全部填充为1
arr11 = np.ones((5,3))   #创建五行三列全为1的数组
print(arr11)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### 随机数模块
- 手动创建数组往往达不到要求，numpy提供了强大的生成随机数的功能
- 与随机数相关的函数都在random模块中，其中包含了可以生成服从多种概率分布随机的函数
- 以下是random函数最常见的生成随机数的方法

In [62]:
ran_1 = np.random.random(10)   #生成10个随机数，每次执行结果都不一样
print(ran_1)

[0.48127623 0.36933585 0.73928881 0.53902642 0.80568824 0.55716635
 0.73936937 0.37069847 0.98587863 0.02308404]


In [67]:
#生成服从正态分布的随机数
ran_2 = np.random.randn(10,5)  #生成10行5列服从正态分布的随机矩阵
print(ran_2)

[[-1.04507631 -1.58336544 -0.43297548  1.08908973  2.04925735]
 [ 0.61833105  1.17232592  0.02939649 -0.03263147  1.44840523]
 [ 0.19768341  0.21221708 -0.10614314 -0.40254615  0.93581698]
 [-0.50170946  0.27370432  1.37615823  1.76457831  1.63892777]
 [ 0.09972512 -2.52665219 -0.70690784 -0.18569487 -1.59246498]
 [-0.0894842  -0.7316969  -0.29964371 -0.09318588 -1.73077169]
 [ 0.51337396  1.34809369  0.17095406  0.37647126  0.15879167]
 [-0.93012038  0.83274069 -0.15167772  1.57882226  0.87106034]
 [ 0.68032065  0.72761229  0.86344134 -0.03948463 -0.34206821]
 [-0.22672051  1.50517205  1.70763102  0.5033883  -1.56937406]]


In [68]:
#生成服从均匀分布的随机数
ran_3 = np.random.rand(10,5)
print(ran_3)

[[0.11930781 0.36429115 0.94569469 0.05964557 0.28184952]
 [0.70589232 0.09670418 0.06770193 0.61697354 0.23610697]
 [0.61403779 0.52166172 0.60570958 0.72644933 0.5584894 ]
 [0.79483217 0.38346914 0.85992489 0.02773583 0.57154781]
 [0.29134758 0.2577382  0.28677257 0.50661361 0.25369635]
 [0.64978039 0.82851479 0.42589059 0.74358458 0.15611768]
 [0.54371795 0.27973318 0.31345884 0.44226611 0.88358934]
 [0.29836322 0.04575591 0.00894217 0.49288747 0.50877322]
 [0.76732225 0.21200842 0.62592384 0.57179296 0.30951462]
 [0.37585968 0.97296602 0.89597801 0.694317   0.75124011]]


In [71]:
#randint函数生成给定上下限制范围的随机数
#格式  np.random.randint(low, high=None, size=None, dtype='l')
#其中low为最小值，high为最大值，size为数组的维数(shape)
ran_4 = np.random.randint(2,10,size=(2,5))
print(ran_4)

[[5 7 3 9 6]
 [3 4 8 8 8]]


#### random模块常用随机数生成函数
- seed：确定随机数生成器的种子
- permutation:返回一个序列的随机排列或返回一个随机排列的范围
- Shuffle：对一个序列进行随机排序
- binomial：产生一个二项式分布的随机数
- normal：产生正态(高斯)分布的随机数
- beta：产生beta分布的随机数
- unigorm：产生在[0,1]中均匀分布的随机数

#### 数组数据类型
- numpy的基本数据类型及其取值范围

#### 数组类型转换

In [2]:
print('转换结果为：',np.float(42))   #整形转换为浮点型

转换结果为： 42.0


In [3]:
print('转换结果为：',np.int8(42.0))  #浮点型转换为整形

转换结果为： 42


In [4]:
print('转换结果为：',np.bool(42))  #整形转换为布尔型

转换结果为： True


In [5]:
print('转换结果为：',np.bool(0))   #整形转换为布尔型

转换结果为： False


In [6]:
print('转换结果为：',np.float(True))   #布尔型转换为浮点型

转换结果为： 1.0


In [7]:
print('转换结果为：',np.float(False))   #布尔型转换为浮点型

转换结果为： 0.0


#### 自定义数据类型

In [8]:
#创建数据类型
student = np.dtype([("name",np.str_,40),("age",np.int64),("height",np.float64)])
print('数据类型为：',student)

数据类型为： [('name', '<U40'), ('age', '<i8'), ('height', '<f8')]


In [9]:
#查看数据类型
print('数据类型为：',student['name'])
print('数据类型为：',np.dtype(student['name']))

数据类型为： <U40
数据类型为： <U40


In [11]:
#自定义数组数据
items = np.array([("小明",18,175.6),('小红',16,165.8),('小王',21,188.0)])
print('自定义数据为：\n',items)

自定义数据为：
 [['小明' '18' '175.6']
 ['小红' '16' '165.8']
 ['小王' '21' '188.0']]
